### PR TITLE
CentOS7 systemd related fixes

### PR DESCRIPTION
**Pull request by n3gster**
Hi. I'd appreciate someone going over this (I'm not an rpm packaging expert). Fixes for statsite user creation and systemd pid dir persistence using /etc/tmpfiles.d/....tested on CentOS7

### CODE REVIEW

**Comment by armon** [comment]
@tuxmonteiro @st-isidore-de-seville Maybe you guys could review this?

**Comment by st-isidore-de-seville** [comment]
@armon, I can review the PR this evening.

**Comment by st-isidore-de-seville** [comment]
@n3gster @tuxmonteiro @armon:

Hey guys, in the PR I see a couple of things worthy to point out.  When building RPM packages I generally defer to: https://fedoraproject.org/wiki/How_to_create_an_RPM_package.  So most of my commentary will come from that.  

In creating users/groups in RPM package, the preferred format is (https://fedoraproject.org/wiki/Packaging:UsersAndGroups):

```
Requires(pre): shadow-utils
[...] 
%pre
getent group GROUPNAME >/dev/null || groupadd -f -g ALLOCATED_GID -r GROUPNAME
if ! getent passwd USERNAME >/dev/null ; then
    if ! getent passwd ALLOCATED_UID >/dev/null ; then
      useradd -r -u ALLOCATED_UID -g GROUPNAME -d HOMEDIR -s /sbin/nologin -c "Useful comment about the purpose of this account" USERNAME
    else
      useradd -r -g GROUPNAME -d HOMEDIR -s /sbin/nologin -c "Useful comment about the purpose of this account" USERNAME
    fi
fi
exit 0
```

Additionally there are prescriptive guidelines around how to create tmpfiles.d in the RPM package using the `%{_tmpfilesdir}` macro (https://fedoraproject.org/wiki/Packaging:Tmpfiles.d)

Lastly with regard to the systemd service unit, I am not sure `StandardOutput` and `StandardError` are necessary because by default systemd logs to journald which in turn logs to syslog.  Also based on https://fedoraproject.org/wiki/Packaging:Tmpfiles.d, they discuss that systemd service units should not care for creation of the tmpfiles.  

I have meaning to submit a PR for a while as well to help out with the SPEC file and to eliminate some of the rpmlinting issues I have had.

**Comment by st-isidore-de-seville** [comment]
@tuxmonteiro @armon:

In thinking about the RPM packaging in this repo and the following https://github.com/armon/statsite/issues/173 issue, I am wondering if the RPM packaging piece is really a downstream activity that should be in a separate repo.  The reason I mention this is because the RPMs can be released in a separate cadence and RPMs actually released using GH releases.  Additionally it would avoid issues like https://github.com/armon/statsite/pull/157 where you modified source code because of the packaging techniques of SunOS where RPM actually complains that the scripts do not contain the shebang.  

Just food for thought.

**Comment by armon** [comment]
@st-isidore-de-seville I'm happy to let the community either move it to another repository or leave it here if that is more convenient. Either way, it looks like the review feedback was addressed so I will go ahead and merge this.

Thanks folks!

**Pull request merged**
