### PR TITLE
dynamically link against libev if available

### PR DESCRIPTION
**Pull request by filippog**
see #110

### CODE REVIEW

**Comment by armon** [comment]
I actually much prefer the static linked approach, as we do not have to worry about conflicts with the OS version, compatibility issues etc. It also reduces the number of issues we need to triage as maintainers.

**Comment by filippog** [comment]
distributions usually prefer dynamic linking, what about doing it optionally instead of autodetecting?

**Comment by armon** [comment]
Is this an issue currently with a distro? Most distro packages have been okay with it so far

**Comment by filippog** [comment]
there's an effort to package statsite for debian, for example I can imagine the debian security team prefers dynamically linked libraries over embedded copies. Would an option to attempt dynamic linking (off by default) work?

**Comment by armon** [comment]
@filippog as a last resort that is fine, but let's not preemptively do it. If it becomes an issue with the security team, then let's cross the bridge. This is a very small C project and honestly it's quite annoying to deal with dynamic linking especially as version changes can break APIs.

**Comment by filippog** [comment]
@armon thanks for the explanation, I agree in general it can be more difficult to support users with dynamic linking, versions, APIs, etc. Given that debian has a much more controlled set of libraries and versions I'm leaning towards dynamic linking there.

Anyways, what do you think about other commits in the branch? all but 4a0887f48 could be applied indipendently I think?

**Pull request closed without merging**
