### PR TITLE
Converted project to autotools

### PR DESCRIPTION
**Pull request by johnkeates**
So, here it goes! I have managed to convert it to autotools. It's currently building, testing, running, travis-ci is happy and the binary you get at the end works too.

I have tested this on Debian and OSX, but I don't have SunOS so I can't test it there.

Scons is still in there as well, when you make test it uses scons to run and test it. Travis's build also uses the integration tests.

There may be a few more things to do:

- Make the tests go via autotools as well
- Verify the RPM build still works
- Update documentation for developers

At this moment, usage is reasonably simple: 

1. From a fresh clone, simply execute ./bootstrap.sh 
2. Execute ./configure and make to get the binary

When pushing to git, so far it seems best to 'make distclean' so you don't get build artefacts in to the tree. I tried adding as many of them to .gitignore as possible but some seem to not get picked up or maybe I mistyped them.

Once this is merged I'll setup Debian/Ubuntu packaging using Debian's guidelines.

### CODE REVIEW

**Comment by armon** [comment]
@johnkeates I had to remove ` -lrt` from the Makefile.am to make this compile on OSX. Scons was special casing that for Linux. Do you know how we can do the proper special casing per OS?

Also, any files generated by the bootstrap, can we avoid having those checked in, since it appears they get regenerated anyways. Thanks!

**Comment by johnkeates** [comment]
Fixed it! I also added some libtoolize vs. glibtoolize detection. If none are found it usually means the autotools setup doesn't need it, but if one is found, it gets run. If both are found, glibtoolize is run.

-lrt is only added if librt if found, autocheck takes care of that.

**Comment by johnkeates** [comment]
And I now also added support for the make install and make uninstall methods. It currently seems to default to /usr/local/share/statsite/sinks for the sinks and /usr/local/bin/statsite for the binary. It is actually possible to change this when you run ./configure as a user; it basically takes the defaults or whatever you specify there. The default it's currently set to is FHS-compatible.

**Comment by armon** [comment]
This looks super great, thanks!

**Pull request merged**
