### PR TITLE
make the binary protocol with the backend respect the extended counters flag

### PR DESCRIPTION
**Pull request by squirrely**

### CODE REVIEW

**Comment by armon** [comment]
@squirrely The extended counters only affected the ascii protocol by design, the binary protocol attempts to provide all the keys.

**Comment by squirrely** [comment]
That means that you have inconsistent behavior by switching the protocol. We have some keys with some 'fun' values in there. This means that we want the be able to use the binary protocol instead of nasty regexes, but we need to be able to control if we get those extra value_types

**Comment by armon** [comment]
@squirrely The ascii protocol tries to be more compatible with the statsd implementation. With the binary protocol, can't you just drop the metrics you don't care about in the sink?

**Comment by armon** [comment]
One of the issues is that this is now a backward incompatible change for use cases that already depend on this behavior which makes it something I'd rather avoid.

**Comment by squirrely** [comment]
I agree that backward compatibility is important to maintain. I think that if people are hard versioning (or using a SHA like we are), that this is a non-issue. 

I think that the best way we could resolve this is to update the docs and cut a release without this change. Then merge this in. This would allow people stick their version and not break functionality. If after this change they wanted to have this functionality it would be a simple config change. 

Other than that we could implement a new flag (extended_counters_binary) and toggle that to be consistent with current behavior (true) and update the docs. This would allow us to control this behavior explicitly. 

Personally I am a fan of the prior, but I would like to see this capability.

**Comment by armon** [comment]
@squirrely Okay, so I'd say lets go with the `extended_counters_binary` and default it to true. That gives you the controls you need and preserves backwards compatibility.

**Comment by armon** [comment]
Closing due to inactivity. Please re-open with a new PR.

**Pull request closed without merging**
